# This is a basic workflow to help you get started with Actions

name: 'build-test'

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: Automation Test
    runs-on: windows-latest # The type of runner that the job will run on
    steps:
    
      - name: Checkout from PR branch
        uses:  actions/checkout@v2

      - name: Installing node_modules
        run:  npm install
        
      - name: Build GitHub Acton
        run: npm run build
        
      - name: Run Unit and Functional Tests
        run: npm run test

